spring:
  application:
    name: replace-table-name
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: pswd123456
    maximumPoolSize: 10
    minimumIdle: 2
    idleTimeout: 600000
    connectionTimeout: 30000
    maxLifetime: 1800000

server:
  port: 8067

mybatis-plus:
  type-aliases-package: cn.studymachine.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


