spring:
  application:
    name: example4
  main:
    allow-bean-definition-overriding: true
  datasource:
    dynamic:
      primary: master
      lazy: false
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice_master?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password: pswd123456
          maximumPoolSize: 10
          minimumIdle: 2
          idleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice_slave1?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password: pswd123456
          maximumPoolSize: 10
          minimumIdle: 2
          idleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000
        slave_2:
          url: jdbc:mysql://127.0.0.1:3306/spring_cloud_alibaba_practice_slave2?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
          username: root
          password: pswd123456
          maximumPoolSize: 10
          minimumIdle: 2
          idleTimeout: 600000
          connectionTimeout: 30000
          maxLifetime: 1800000

server:
  port: 8067


mybatis-plus:
  type-aliases-package: cn.studymachine.mapper
  mapper-locations: classpath:mapper/*.xml



